import type { Metadata } from 'next';
import React from 'react';
import { ThemeProvider } from './contexts/ThemeContext';
import './globals.css';


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <ThemeProvider>
                <body className='body'>{children}</body>
            </ThemeProvider>
        </html>
    );
}
